# Generated by Django 4.0.5 on 2022-06-29 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docto_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_degree', models.CharField(max_length=100)),
                ('doctor_speciality', models.CharField(max_length=100)),
                ('doctor_start_time', models.CharField(max_length=100)),
                ('doctor_end_time', models.CharField(max_length=100)),
                ('doctor_fees', models.PositiveIntegerField()),
                ('doctor_picture', models.ImageField(upload_to='doctor_picture/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
