# Generated by Django 4.0.5 on 2022-06-30 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_docto_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Docto_Profile',
            new_name='Doctor_Profile',
        ),
    ]
