# Generated by Django 4.0.5 on 2022-07-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_docto_profile_doctor_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subject',
        ),
    ]
